/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  sideBar: [
    'introduction',
    'codebase',
    {
      type: 'category',
      label: 'Udacity Intermediate Python Projects',
      collapsible: true,
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'intermediate_python'}]
    },
    {
      type: 'category',
      label: 'Udacity ML Engineer Projects',
      collapsible: true,
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'ml_engineer_projects'}]
    },
    {
      type: 'category',
      label: 'Udacity ML DevOps Projects',
      collapsible: true,
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'ml_devops_projects'}]
    },
  ],
};

module.exports = sidebars;
