name: randon_forest_model
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas==2.0.3
  - pip==23.2.1
  - scikit-learn=1.3.0
  - matplotlib=3.7.2
  - plotly=5.16.1
  - pillow=10.0.0
  - mlflow==2.5.0
  - pip:
      - wandb==0.15.8
      - omegaconf==2.3.0
