"""empty message

Revision ID: b0822bf0ee03
Revises:
Create Date: 2023-10-05 14:38:51.151908

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0822bf0ee03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shows')
    op.drop_table('artists')
    op.drop_table('venues')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
                    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('venues_id_seq'::regclass)"), autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('city', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
                    sa.Column('state', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
                    sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
                    sa.Column('phone', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
                    sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
                    sa.Column('facebook_link', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
                    sa.Column('seeking_talent', sa.BOOLEAN(), autoincrement=False, nullable=False),
                    sa.Column('seeking_description', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('website_link', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('genres', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='venues_pkey'),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('artists',
                    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('artists_id_seq'::regclass)"), autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('city', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
                    sa.Column('state', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
                    sa.Column('phone', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
                    sa.Column('genres', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
                    sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
                    sa.Column('facebook_link', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
                    sa.Column('website_link', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('seeking_venue', sa.BOOLEAN(), autoincrement=False, nullable=False),
                    sa.Column('seeking_description', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='artists_pkey'),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('shows',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
                    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name='shows_artist_id_fkey'),
                    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name='shows_venue_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='shows_pkey')
                    )
    # ### end Alembic commands ###
